name: client_server_sockets
description: A simple client-server sockets wrapper package around the Socket and the ServerSocket classes.
version: 1.1.1
repository: https://github.com/georges-ph/client_server_sockets
issue_tracker: https://github.com/georges-ph/client_server_sockets/issues

environment:
  sdk: ^3.10.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
